"""Added timestamp to orders

Revision ID: 49817a4b0323
Revises: a2a947d4afd4
Create Date: 2025-03-14 14:45:34.330703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49817a4b0323'
down_revision = 'a2a947d4afd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
