"""Remove temp_column from user table

Revision ID: f310576e3200
Revises: 22b5ae907c7f
Create Date: 2025-03-09 01:24:49.414068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f310576e3200'
down_revision = '22b5ae907c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('temp_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_column', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
